# Generated by Django 6.0.7 on 2026-07-11 17:08

import common.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bannedip_user_registration_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(blank=True, choices=[('influencer', 'Influencer verificado'), ('ator', 'Ator profissional (DRT)')], max_length=20),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('influencer', 'Influencer verificado'), ('ator', 'Ator profissional (DRT)')], max_length=20)),
                ('drt_numero', models.CharField(blank=True, max_length=30)),
                ('justificativa', models.TextField(blank=True)),
                ('documento', common.images.SanitizedImageField(blank=True, null=True, upload_to='verificacao/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_verificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
