# Generated by Django 6.0.7 on 2026-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_verified_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='drt_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
