sonar.projectKey=dublacon
sonar.projectName=DublaCon
sonar.sources=backend,frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**,**/.venv/**,**/dist/**,backend/seed.py
sonar.test.inclusions=backend/**/tests.py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
