# Generated by Django 6.0.7 on 2026-07-10 23:23

import common.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='capa',
            field=common.images.SanitizedImageField(blank=True, null=True, upload_to='capas_projeto/'),
        ),
    ]
