# Generated by Django 6.0.7 on 2026-07-11 01:46

import common.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='foto',
            field=common.images.SanitizedImageField(blank=True, null=True, upload_to='updates_projeto/'),
        ),
    ]
