# Generated by Django 6.0.7 on 2026-07-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project'),
        ),
    ]
