# Generated by Django 6.0.7 on 2026-07-11 17:01

import common.images
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectupdate_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='audio',
            field=common.images.SanitizedFileField(blank=True, null=True, upload_to='testes_voz/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
