# Generated by Django 6.0.7 on 2026-07-10 23:23

import common.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='screenshot',
            field=common.images.SanitizedImageField(blank=True, null=True, upload_to='bug_reports/'),
        ),
        migrations.AlterField(
            model_name='reportevidence',
            name='foto',
            field=common.images.SanitizedImageField(upload_to='denuncias/'),
        ),
    ]
