# Generated by Django 6.0.7 on 2026-07-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_bugreport_screenshot_alter_reportevidence_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('candidatura_aceita', 'Candidatura aceita'), ('candidatura_recusada', 'Candidatura recusada'), ('nova_mensagem', 'Nova mensagem'), ('novo_comentario', 'Novo comentario'), ('nova_avaliacao', 'Nova avaliacao'), ('denuncia_atualizada', 'Denuncia atualizada'), ('novo_seguidor', 'Novo seguidor')], max_length=30),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='segue_uma_vez')],
            },
        ),
    ]
