# Generated by Django 6.0.7 on 2026-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('candidatura_aceita', 'Candidatura aceita'), ('candidatura_recusada', 'Candidatura recusada'), ('nova_mensagem', 'Nova mensagem'), ('novo_comentario', 'Novo comentario'), ('nova_avaliacao', 'Nova avaliacao'), ('denuncia_atualizada', 'Denuncia atualizada'), ('novo_seguidor', 'Novo seguidor'), ('verificacao_atualizada', 'Verificacao atualizada')], max_length=30),
        ),
    ]
